---
:consumer_key: "mJ5otbhPGNoDCgCL7j5g"
:consumer_secret: "M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg"
:access_token: "3037874127-x06nazv66yH9N3nv61dLgExjYpWIGieZhwVgMwo"
:access_token_secret: "2zGnihazfgmkEWvOMsn4OO8fsJJzcsHsPT9qmuqn0pUb3"
